### ISSUE TITLE
Question about running simulator and generating offline training data

### ISSUE THREAD

**Issue by YANGxinyu418** [chengkaiAcademyCity/EnvAwareAfford#2]
Hello, thank you very much for your excellent research work. However, I have encountered some problems while running your code recently, so I would like to ask for your help.

1. When I run the "collect_data.py" file located in the "code" folder under the  "[Simulator](https://github.com/chengkaiAcademyCity/EnvAwareAfford/tree/main/code#simulator)" , I get an error: Traceback (most recent call last):

```
Traceback (most recent call last):
  File "collect_data.py", line 435, in <module>
    loop_cnt += 1
NameError: name 'loop_cnt' is not defined
```

I tried to locate the error and found that changing the `loop_cnt` variable in the collect_data.py file from line 413-437 to `robotloop_cnt` allowed the code to run normally. I was wondering if there is a better solution to this problem?
The original code is as follows. Could you tell me how this problem occurred?
![image](https://github.com/user-attachments/assets/83d0b741-4104-4d27-87f7-b51675e81362)

2, When I run the `scripts/run_gen_offline_data.sh` script, all of my output data is `"cmd fail [-1]"`. I wonder how this happened? I have downloaded and properly stored the data according to the instructions in the data folder's readme file.
![image](https://github.com/user-attachments/assets/8d5bed60-9557-40ef-ac13-37d6c775d5cb)

I would greatly appreciate it if you could reply in a timely manner. Thank you again for your wonderful work.

**Comment by chengkaiAcademyCity** [comment]
Hi Xinyu,

Thank you for reaching out and for your interest in our work. We appreciate your feedback.

1. Thanks for pointing out the bug in variable`loop_cnt`. The `collect_data.py` has been updated.

2. `cmd fail` means that this particular data point encounters object clipping in the scene. Our scene configuration is implemented by putting objects one by one, which may clip with each other. When this happens, we disgard such a data point and print `cmd fail`, see #1 .

Thanks and hope your experiments go well!
